import type { ComponentType, ComponentProps } from 'react'
import {
  AnnotationIcon,
  ClockIcon,
  CodeIcon,
  ChatIcon,
  ChatAltIcon,
  CloudIcon,
  DesktopComputerIcon,
  IdentificationIcon,
  LightningBoltIcon,
  LocationMarkerIcon,
  DatabaseIcon,
  EmojiHappyIcon,
  FilmIcon,
  MailIcon,
  MapIcon,
  MoonIcon,
  GlobeIcon,
  DocumentIcon,
  PhotographIcon,
  LinkIcon,
  HandIcon,
  ShareIcon,
  SunIcon,
  ChatAlt2Icon,
  NewspaperIcon,
  QuestionMarkCircleIcon,
  QrcodeIcon,
  CurrencyDollarIcon,
  TerminalIcon,
  TicketIcon,
  TrendingUpIcon,
  RssIcon,
  SearchIcon,
  TranslateIcon,
  TruckIcon,
  VideoCameraIcon,
  UserIcon,
  UserCircleIcon,
  UserGroupIcon,
  BanIcon,
  ViewListIcon,
} from '@heroicons/react/outline'

type Icons = Record<string, ComponentType<ComponentProps<'svg'>> | undefined>

export const ICONS: Icons = {
  address: LocationMarkerIcon,
  answer: QuestionMarkCircleIcon,
  app: TerminalIcon,
  avatar: UserCircleIcon,
  cache: DatabaseIcon,
  carbon: CloudIcon,
  chat: ChatAltIcon,
  contact: UserGroupIcon,
  comments: AnnotationIcon,
  crypto: MoonIcon,
  currency: CurrencyDollarIcon,
  db: DatabaseIcon,
  email: MailIcon,
  emoji: EmojiHappyIcon,
  evchargers: LightningBoltIcon,
  event: ShareIcon,
  file: DocumentIcon,
  forex: CurrencyDollarIcon,
  function: CodeIcon,
  geocoding: LocationMarkerIcon,
  gifs: PhotographIcon,
  google: SearchIcon,
  helloworld: HandIcon,
  holidays: SunIcon,
  id: DesktopComputerIcon,
  ip: DesktopComputerIcon,
  image: PhotographIcon,
  joke: EmojiHappyIcon,
  lists: ViewListIcon,
  location: LocationMarkerIcon,
  memegen: EmojiHappyIcon,
  minecraft: GlobeIcon,
  movie: FilmIcon,
  mq: ShareIcon,
  news: NewspaperIcon,
  nft: TicketIcon,
  notes: DocumentIcon,
  otp: IdentificationIcon,
  ping: GlobeIcon,
  place: MapIcon,
  postcode: LocationMarkerIcon,
  prayer: GlobeIcon,
  quran: GlobeIcon,
  qr: QrcodeIcon,
  routing: LocationMarkerIcon,
  rss: RssIcon,
  search: SearchIcon,
  sentiment: DesktopComputerIcon,
  sms: ChatIcon,
  space: DatabaseIcon,
  spam: BanIcon,
  sunnah: GlobeIcon,
  stock: TrendingUpIcon,
  stream: ChatAlt2Icon,
  thumbnail: PhotographIcon,
  time: ClockIcon,
  translate: TranslateIcon,
  twitter: DesktopComputerIcon,
  url: LinkIcon,
  user: UserIcon,
  weather: SunIcon,
  vehicle: TruckIcon,
  youtube: VideoCameraIcon,
}
