name: Run tests
on:
  push:
    paths:
      - 'go.mod'
      - 'go.sum'
      - 'cmd/**'
      - '**.go'

jobs:

  test:
    name: Test repo
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go

    - name: Install Protoc
      uses: arduino/setup-protoc@master

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Run tests
      id: tests
      env:
        IN_TRAVIS_CI: yes
      run: go test -v ./...

